#!/usr/bin/env bash

set -x  # debugging flag is on 
  # if you dont put set +x on bottom it will debug whole file 

first_name='dave'
last_name='eddy'

full_name="$first_name $last_name"

set +x  # debugging flag turned off 

if [[ $first_name == 'dave' ]]; then
	echo "oh hey it's dave"
fi

echo "Hello $full_name!"
