#!/usr/bin/env bash

process-indexed() {
	local arguments=("$@")
	echo "found: ${#arguments[@]} arguments"

	local IFS=,
	echo "${arguments[*]}"
}

process-associative() {  # it deduplicates data 
	local arguments=("$@")
	echo "found: ${#arguments[@]} total arguments"

	declare -A unique
	local item
	for item in "${arguments[@]}"; do
		unique[$item]=1
	done

	echo "found: ${#unique[@]} unique arguments"
}

process-commands() {
	local arguments=("$@")
	echo "found: ${#arguments[@]} total arguments"

	local item
	for item; do  # here if you dont use 'in' in for loop, the for loop will loop over the arguments -> $1 -> $2 -> $3 till nothing
		echo "running command: $item"
		"$item" # hmmm
	done
}

cmd=$1
echo "script called with arguments: $*"
shift  # its an command to move arguments over by one on left side
echo "script shifted to arguments: $*"

case "$cmd" in
	indexed)
		process-indexed "$@"
		;;
	associative)
		process-associative "$@"
		;;
	commands)
		process-commands "$@"
		;;
	*)
		echo "unknown cmd: $cmd" >&2
		exit 1
		;;
esac
